version: 2

jobs:
  build:
    docker:
      - image: quay.io/giantswarm/golang:1.12.9
    working_directory: /workdir
    steps:
    - checkout

    - attach_workspace:
        at: .
    - restore_cache:
        keys:
          - go-mod-v1-{{ checksum "go.sum" }}

    - run: |
        CGO_ENABLED=0 go test -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" ./...

    - run: |
        CGO_ENABLED=0 go build -ldflags "-w -X main.gitCommit=${CIRCLE_SHA1} -linkmode 'auto' -extldflags '-static'" -o e2ectl .

    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
          - "/go/pkg/mod"

    - run: |
        ./e2ectl version

    - persist_to_workspace:
        root: .
        paths:
          - ./e2ectl 

  github-release:
    working_directory: /home/circleci/.go_workspace/src/github.com/giantswarm/e2ectl
    machine: true
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: ./github-release.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1 $PERSONAL_ACCESS_TOKEN

workflows:
  version: 2
  build_e2e:
    jobs:
      - build
      - github-release:
          requires:
            - build
          filters:
            branches:
              only: master
